namespace FactoryShield.Application.Incidents.Models;

public record IncidentDetailDto(
    Guid Id,
    string IncidentReference,
    string Category,
    int Severity,
    string DisplayStatus,
    string ShortDescription,
    string? Department,
    DateTime CreatedAt,
    string? ReporterDisplay,
    string? AssignedTo,
    DateTime? SlaStartedAt,
    int? SlaTargetMinutes,
    string? SlaStage,
    bool IsConfidential,
    int EscalationLevel,
    string SourceChannel,
    string? RejectReason,
    string? ClassificationCategory = null,
    string? SubCategory = null,
    string? Factory = null,
    string? Building = null,
    string? Floor = null,
    string? Equipment = null,
    string? ProductionOrder = null,
    string? Buyer = null,
    string? StyleNumber = null,
    DateTime? IncidentOccurredAt = null,
    string? ReporterName = null,
    string? EmployeeId = null,
    string? ReporterDepartment = null,
    string? ContactNumber = null,
    string? Witnesses = null,
    string? ImmediateActionTaken = null,
    string? ExactLocation = null,
    string? GpsCoordinates = null,
    string? AiSummary = null
);